apiVersion: v1
kind: Service
metadata:
  labels:
    app: log-parser
  name: log-parser-service
  namespace: default
spec:
  ports:
  - nodePort: 30892
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: log-parser
  sessionAffinity: None
  type: LoadBalancer
