apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
  namespace: default
spec:
  ports:
  - nodePort: 30893
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: app
  sessionAffinity: None
  type: LoadBalancer
